# Shared with Add-in Playground
---
id: ''
gist: ''
author: Microsoft
source: OneNote
name: New Snippet
description: |-
    Sample snippet to demonstrate the use of the Add-in Playground for OneNote.

script:
  language: typescript
  content: |-
    $('#run').click(function () {
        invokeRun().catch(OfficeHelpers.Utilities.error);
    });

    function invokeRun() {
        return OneNote.run(function(context) {
            // Insert your code here. For example:
        });
    }

style:
  language: css
  content: |-
    .ms-Button, .ms-Button:focus {
        background: #217346;
        border: #217346;
    }

    .ms-Button > .ms-Button-label,
    .ms-Button:focus > .ms-Button-label,
    .ms-Button:hover > .ms-Button-label {
        color: white;
    }

    .ms-Button:hover, .ms-Button:active {
        background: #164b2e;
    }

template:
  language: html
  content: |-
    <p class="ms-font-m">Execute a code snippet in the Add-in Playground for OneNote</p>
    <button id="run" class="ms-Button">
        <span class="ms-Button-label">Run code</span>
    </button>

libraries: |-
    // Office.js CDN reference
    https://appsforoffice.microsoft.com/lib/beta/hosted/office.js

    // Other CDN references.
    // Syntax: NPM package name, NPM package path, or raw URL to CDN location.
    core-js/client/core.min.js
    jquery
    @microsoft/office-js-helpers
    office-ui-fabric-core/dist/css/fabric.min.css
    office-ui-fabric-js/dist/css/fabric.min.css

    // IntelliSense definitions.
    // Syntax: "dt~library_name" for DefinitelyTyped, "@typings/library_name" for Typings, or raw URL to d.ts location.
    dt~core-js
    dt~jquery
    dt~office-js
    @microsoft/office-js-helpers/dts/office.helpers.d.ts
