language: node_js
cache:
  directories:
  - node_modules
node_js:
- 6.9.4
install:
- npm install
script:
- npm run build-dev
before_deploy:
- rimraf node_modules
deploy:
- provider: azure_web_apps
  verbose: true
  site: bornholm
  slot: bornholm-edge
  skip_cleanup: true
  on:
    branch: build
env:
  global:
  - secure: uBVc67b8dOwOegjet861k8R2ryn/P7BqksZO3v2z/JhbYwhEyBzBCLrEhRob8jhdtZT8aH6c7ZBgkHTcK5gpRZPDneyNjtgzjv5EG2Vwo5AoUaKM54pUkC+z6o491bartA+2go+kKCgjSQo+vFXGpeOJPvbhUEzgjxR5PUscTyOyRQqzNbOc/YcALT8uoMgVdMdhjgv6XhDx1VciZqxIWCZ/WCGtMXQQBmgdE3121PQtbVJ5DfSGfVcXdxBLHvpX5Nop3azYiJK/r39hDWJurLiB5GRSqKWtkvnqNpzeKBQB2j+IsLkD4utWO/476Gq9JundveIUeGRwy1NLUu8UCRL5dZGimgPySWvP4DH7JNHE+Our+AGN2Ct549kVfUdmp67gvLnFo6sc1SeeIWeuHYQdNmWBbZIEV10hUPmAXY6KxdVWGpFH0bH/y1klhsXyIpddTo/a3XTWfMUrsnQLMREfKgjgSPoCY/IXORs9xn7KefAlGFMY2BC5+nH+odkp7/40BeoELMeECqATepB/tVl7oK55DzBr/Qd+IkW1dDsmfFZQoKBmT9E4CE8s+DqRUVCTMhu2xDT9cUJwUV+eMnljJpEzj1X5eBCs5ulN5u7VZddt+C5wMv8CLWYcBc5BTRAIIK7sTrey9y+K+53Cez/IZ7vR/tB1/lzn5jVfQRQ=
  - secure: ye9tCRq7fB6Nqkwq4WPlfRuO6Xlp9LpqllGBMth8iEU2SI6CtsTffhmxhg7LP9iWxQQ1bnjsP+MwfqxFwlCRQPwKNZRgkmSyuJ4N846y7CtOqbiDZjv7EoIdeNR3rM3PIK8eI8D7R89HcKme/LoSvgXVKgaW9I1c1lHzH7WhT38Z16p7uVXVsvy+6oFysvo8itinZC06oL1HnYPURponfgeIXPYGrryQugfhmetYASCAFu0dZto61nSSArpudX7Ym+nJ5Km9l+IvN0mlBEDGJipVruqH8KCbM7g12oqOCOTHKgvWasj5WQjVpDDHj3BMzATQJReLJNAs6WTe1FkdzCV5kR3Tf96+VJwdcRYofu/7L4apbA3vipm0Z2pN/UG030IYDy+rlv7GZTQZ5V9BcH1YiqZOhqh/+1D8aEWoXfNgUiJZlN3YkR82urMtPlvwsT8cidXQvP0mWsoi7xIu962nmtOWYcQUeo87j/gG9H2FhvgILlRHPuj/5PWA4YM97YFtOHMK9FKA0fFoQc87gfJ+rnvik0bm9If3oto+7o/R9SBaVkyRUn42Qm1Xch7nYvSFFGSE8dR44UtKPt6KOqpqQNf9Ahj/8E7oSCUvjlcObQGYVQh3GFEKFEtWLNICY69cdCVLf/oeEyXaZnKaE/0YJ+V0eDsdm3foMYnImOg=
