language: node_js

cache:
  directories:
  - node_modules

node_js:
- 6.9.4

install:
- npm install

script:
- npm run build-dev

before_deploy:
- rimraf node_modules

deploy:
- provider: azure_web_apps
  verbose: true
  username: bhkrish
  password:
    secure: dTr8BU4MA4IszqHOIL3KVGP/Qej7txzg46Dy5jISbDOylLh7bKrCFniwKushMUByJ0dnGil8B0oVmz6shfwJTxANxmfUIG3R2R6FqcdSXVC2si7qZwyO73Bu0pSHQ+ELhRPX5SEPy3hzW2r8yBEKnU7eYSQoHPgY8Mv3aMhseRMOv63ADBdXHcoMhd+eIPY/MSrx09ixzhciKsi43qMiyaWNSSMFdS/Xtdw8QnovHzDgb0ag2ISN9TbGhZieDhA3msZ8UrE1wFCZjqL7NGRiVIBxqPZMj0srVeunOiH4qdfPj5ZcKULeDj1a+s7vNIoocOuYVwCbePJ3mr0UK0ZRKMTJJfX4E2nKRyMDZQVOKX4gAkZB4yFmazR7+NmjpGfCHclHFqVTnBd8QFiLLOtbXKSVaWnEjd4Tl7DFIIn+bhG/5TAAl3cjL4ATC7xeaBDJ5MU1hWkZv5ZX9pST+FQVb9jTOCJBNrw/agI8FstQ+dvZMz1RYxTbleAI5FNf2P4IXR/v/wINWzBM1qKgrV0EG0tzS/0sZ5yq/7oMmlHxSMOuoAkzyT/RJ1s2OxiSUSeOImZhY+vChBB5hkTl4SxlZ7FkTXF2l6bKptLCpGSYmSBuf4a56HBjOBc8yTdGQ49Y8fAqdIVtMHkfi3RpwQ4EeuEVuoT7ImnOZL3rQT9lTuo=
  site: bornholm
  slot: bornholm-edge
  skip_cleanup: true
  on:
    branch: build