language: node_js

cache:
  directories:
  - node_modules

node_js:
- 6.9.4

install:
- npm install

script:
- npm run build-dev

before_deploy:
- rimraf node_modules

deploy:
- provider: azure_web_apps
  verbose: true
  site: bornholm
  slot: bornholm-edge
  skip_cleanup: true
  on:
    branch: build

env:
  global:
  - secure: F+n4z9akpJwEr2K1BrBu8hndggYFq8DNj3nXy1OTfAEFC9bAF2vnN7u3UgRJtjRW8yLMW8+yTSf51nVdQr13VZBT3yA5pXYc8ep+NEZft0xgoX7eMbZ0hq9yTQFOfhnjZ97VbJXjsqApEPrAIlc+pbtHImaucLtIA0uvVs3l/f1nNonvhpIFAtnmob4I09Kg3Uuo0XgDRQztIpxmv3qnMPjusd1jbKa3eCEmjy4UndLPtWwUUZsqPRGnpeP6j3SgJ181IdzY3CwabXV6cK8rBZj0hDUTi0koIPbXYAC07K++24EDl5VHZE17qftVdZb8p5rzVBaOc83OWPLrbyBqnNMsvYVpnXn8OubxogRtzSG3DN3nq20daufLTR31w8LYpyF+zdYVfLFGojJT4koZroeZBmGJ1+JRxTQeSoxzHo+/XPNO6vsDhAEZgbY94DynceexQYfog2sc5MZDROGctQ455+CsGC/gxYdBFdsLcISZZpx2Y9ihk7GjOvFCF1VErv1NOstCwYcPSIfLxVI4E3RMaLqY2ZxvMCTpLHUlZz/ZIMVQojbiI6XmjM0Z+0Igzbmk3u+dtGxArtzJKr9UsJUMqFvm56bspFfHVYWxtn3ikfPnoIjeO0RgyBvJQfwpwKh98OfFiepbJIDZ7ebDnfZVy6UxUmurYYgduYay88E=
  - secure: YYDtI9Cc/2dQlkgaXeDj17lFQhHJXHXZDT6NCfCMSErlFwH81/gotK2zGUFroLd9xERgQzdQ4oHpmonuD85u2M4xdGWuIow6Tx5ElVjxHegVh5mukwry9BPSfjV8CGxkT7W2MpEd/XyONQP0+XjeklTH433fLbUtsIm1l0Q3uZaQcmFi72K7BEK23Ec8kdbLf29liimcFWuxyAe8edOdSlcwnhpyRcqKsbgbe07Rqpki7JEgDg8OUqiHvy+w37/jlM/TTsGMFO22n82i9ufM8qLhiYA95QMy/MfvFQ0EvRN2YTWZKXCytRuKB6I8sK9hPPUXHLUAPLM6Mc838T+xn9jJdIQ/0EiS/hAfr2KgnI7pw+zwd8/PGH10e5OOQYllkPB/XlWgV7Je0OTP71F/oSlo10A7vx/EawIPpfmPZKxl5xNgiGGd3pv/tbv4uQRpCGS8/ETLb6zJUBeQt729uIHxHMxs6Sih06vZluIcsH2hstIUGagG9yugWn6od33UIQkIClphCWjLm9zVwKADzmg4IOqLlpGaEyJ+5jHHHvxzwMdOQt5OnQvXZ0ll5ozTySaRC7jzSGPnW+bK6O3GR4A8MUpI/oOkq6npikYeOqNLayQZ1SKVE5W3z47BaC40vb6FHBqOsI5ZTBerO7IKQWDIpLfrDSau9R8rzyE9GLs=
