language: node_js
cache:
  directories:
  - node_modules
node_js:
- 6.9.4
install:
- npm install
script:
- npm run build-dev
before_deploy:
- rimraf node_modules
deploy:
- provider: azure_web_apps
  verbose: true
  site: bornholm
  slot: bornholm-edge
  skip_cleanup: true
  on:
    branch: build
env:
  global:
  - secure: 5z9kM6L7f8GWRP8M1bmtZ0gwUlM2nhHwG6xKLgDJnvQW6z8tzdmIWogPv/RrTZnCObIUKD9RRiZCIqOD4nzfMBFFWV6nJbK14V0hLcFuhahDr+FVmAVqd/q4zOhbWj4OoqJ7l6//0g12NRnAbZQKYxvjmUrry4ipvcEinoeYlnEqLxzFOArKVRl31CONctCzjZzCUEHgn10iqOZln2N1S3t040hVqSvXj8He8AGs3yTXxbc6LyTMq5pTrKWOpOJHIw81FzW3nPVEi/Xz3EXhgYVHoLuUpMbYxjfGksdZddJ+qn5EtZpQ2ydQbdYzGOi5UFdCdjJ3TcWjwdcJiGU+n/ccxwcqToy9BgYobP371AN4zpz37qDbac7EKyz5TR5v+yyphHP/nW9YXc8KZGwECUO6z6F1RYmkZahXwFEMbRbkGhrrLLDuGckug9oj1F3kEsHsNGwksVksUD5reX7T/UqR3Rh9zEqR77vtPgFC6Hrm4+cUjBwZdiXHrQzx85UtXt5d91tPhU3hFvn+hG9RL8rYwopNDcTa2UonVk0Nq70Ki9qnGce7oV0GadUC7oufid6KskVnpFQf911Ylxiu9P78p4kUVQPjCHlmY+bBr0o7JZIxztBtL9MgiAA0mKsaHtXL2KkRZ0Aa17/UmifN34NYsLpRZwKfkg/ymKt5E4Y=
  - secure: c91pOQ8Oe/TpON41ARlttbi4qoAftiRCjPZg+R1wmoTHvWQNRSCY5MeZNM/Vk1mlSzm39YATEKo/RWyQobtZKv4AM+JmcBh2Jms1gxvyAz7IxXG1+xT0Lgvf0N3vh84KI/NIYmYx/rekMw5r7g3XLS1oSwKgfMA/PA/nYjtsKE/icdNYVmZiEe2aPy+IhpE1NQeM+MQ8VwUd4v6gKPfh6iVKqBgA9Nt894rgqlTTArUvxG0KK/uTapxLEQCUL3ybA+goxmn7n0kQ4j7yOUiuRbc07nR1BELqcgQKtHZHiTsogLJBD+l7Tn6taur4g5+Xey1ToH3GvJpQBKzcvNNe8xpxVt74C9iAinnZse1GkNLx9GWgmLdr5exEAHFnAVYEeHT7bUBvk4FvPse2x3wdMIHFxSiHEs8NzF/2+nuF+0dqDy6vWw96e30aJ97Y93LxDOEHTlripcoMr83MKY4UYFi/zGzs2+p0nsmup3DJhva9YOTrmNFZu70dhk4jypxbRpAbiIuxCziySTWLRx6jGOR8jJOfbCjGHzprZTeFa5Zu1F3Ske67zsuM31TMibjf2jlYhWkDYooAwxMUadDWC8np2cL+kJZeuY607GeG1t31E8AJnFrSoTufMUqVG4p1N987CPeSopoIE2g2TTV67YzJyhFyIBrh8jK1WF3CNyw=
